id = "mcp-server-firecrawl"
name = "Firecrawl MCP Server"
description = "Model Context Protocol Server for Firecrawl"
version = "0.0.3"
schema_version = 1
authors = ["Akbxr <hi@akbxr.com>"]
repository = "https://github.com/akbxr/firecrawl-mcp-zed"

[context_servers.mcp-server-firecrawl]
name = "Firecrawl MCP Server"
